.nais/nais.yaml
.nais/qa-template.yaml
src/main/java/no/nav/sbl/config/ApplicationConfig.java
src/test/java/no/nav/sbl/ApplicationConfigTest.java

registrerer appen i azure, og lar andre lage OBO-token til modiacontextholder.

[KAIZEN-0] legge til azureAd config og inbound policies

---

.nais/nais.yaml
.nais/qa-template.yaml
src/main/java/no/nav/sbl/config/ApplicationConfig.java
src/test/java/no/nav/sbl/ApplicationConfigTest.java

gjøres slik at applikasjonen enkelt kan registreres til azuread og enklere motta OBO-tokens

[PROD][KAIZEN-0] Endrer namespace

---

pom.xml
src/main/java/no/nav/sbl/config/ApplicationConfig.java
src/main/java/no/nav/sbl/config/FeatureToggle.java
src/main/java/no/nav/sbl/config/FeatureToggleConfig.java
src/main/java/no/nav/sbl/service/AuthContextService.java
src/main/java/no/nav/sbl/util/AccesstokenServletFilter.kt
src/main/java/no/nav/sbl/util/AuthContextUtils.kt
src/test/java/no/nav/sbl/EventDAOTest.java
src/test/java/no/nav/sbl/service/AuthContextServiceTest.java

- [KAIZEN-0] bump spring etc
- [KAIZEN-0] fikset unleash setup
- [KAIZEN-0] fikset import for test
- [KAIZEN-0] sette opp accesstoken som servlet filter

[KAIZEN] fix/bump spring common

---

.nais/nais.yaml
.nais/qa-template.yaml
src/main/java/no/nav/sbl/rest/RedirectRessurs.kt

gjøres fordi man må sjekke med unleash hvorvidt en bruker skal sendes med bruker i kontekst (e.g er med i piloten).
Dette gjøres fordi Salesforce ikke støtter urler med bruker i kontekst for brukere utenfor piloten

[PROD][KAIZEN-0] sette opp salesforce redirect

---

.nais/nais.yaml
.nais/qa-template.yaml

- 16d69f5 [KAIZEN-0] legge til modiaflatefs med obo-flyt
- 0855497 [KAIZEN-0] legge til modiaflatefs med obo-flyt

[PROD] [KAIZEN-0] legge til modiaflatefs med obo-flyt-tilgang

---

.nais/nais.yaml
.nais/qa-template.yaml

antar dette er nødvendig for å kunne få tilgang fra appen i GCP :sweat_smile:

add smregistering gcp to inbound rules

---

.nais/nais.yaml
.nais/qa-template.yaml

- 1221e5e add smregistering gcp to inbound rules

[PROD] add smregistering gcp to inbound rules

---

src/main/java/no/nav/sbl/naudit/Audit.kt
src/main/java/no/nav/sbl/util/AuthIntrospectionFilter.kt

[[OPP-1522] Logge referer til tjenestekallloggen](https://github.com/navikt/modiacontextholder/commit/8812bbedb788f523ffafaa98862c1a3a1eed2b6b)

[PROD][OPP-1522] Logge referer til tjenestekallloggen

---

src/main/java/no/nav/sbl/rest/RedirectRessurs.kt

- d7550c4 [KAIZEN-0] legge til bedre feilhåndtering ved kall til aareg

[PROD] [KAIZEN-0] legge til bedre feilhåndtering ved kall til aareg

---

src/main/java/no/nav/sbl/rest/RedirectRessurs.kt

- 146bed8 [KAIZEN-0] bugfix uthenting av request body

[PROD] [KAIZEN-0] bugfix uthenting av request body

---

.nais/nais.yaml
.nais/qa-template.yaml

Ref: https://nav-it.slack.com/archives/C01DE3M9YBV/p1677755077017029?thread_ts=1674475818.557619&cid=C01DE3M9YBV

Gi alle AzureAD-brukere tilgang i prod

---

.nais/nais.yaml
.nais/qa-template.yaml

Vi er i prosess med å migrere frontend-app'ene våre til gcp og tenkte å starte med finnfastlege.

finnfastlege til gcp

---

src/main/resources/application.properties

Vi bruker ikke flyway på fss, så den må kun kjøre på gcp.

Skru av spring sin Flyway autoconfiguration

---

src/main/java/no/nav/sbl/rest/ContextPathRedirect.kt
src/test/java/no/nav/sbl/rest/ContextPathRedirectTest.kt

Vil forhåpentligvis gjøre transition med og uten context path litt smudere :)

Legg til controller for å redirecte fra base path

---

src/main/java/no/nav/sbl/config/ApplicationConfig.kt
src/main/java/no/nav/sbl/rest/ContextRessurs.kt
src/main/java/no/nav/sbl/rest/DecoratorRessurs.kt
src/main/java/no/nav/sbl/rest/DecoratorRessursV2.kt
src/main/java/no/nav/sbl/rest/EventRessurs.kt
src/main/java/no/nav/sbl/rest/RedirectRessurs.kt
src/main/java/no/nav/sbl/util/RewriteContextPathFilter.kt
src/test/java/no/nav/sbl/rest/ContextPathRedirectTest.kt

Reverts navikt/modiacontextholder#318

Revert "Fjerne filter og legg til context match på kontrollere"

---

src/main/java/no/nav/sbl/config/ApplicationConfig.kt

- **Match på flere paths istedenfor filter**
- **Legg til midlertidig prefix på filter url patterns**

Legg til midlertidig prefix på urlPatterns i filtre

---

.nais/dev.yaml
.nais/prod.yaml
src/main/java/no/nav/sbl/rest/FnrCodeExchangeController.kt

Og fikse en dårlig RequestMapping

[TPO-42] Skru på autoInstrumentation

---

pom.xml
src/main/java/no/nav/sbl/azure/AzureADService.kt
src/main/java/no/nav/sbl/config/ApplicationConfig.kt
src/main/resources/application.properties

MS Graph er veldig tregt og mesteparten av tiden i APIet blir brukt på å
vente på ms graph. Dette burde definitivt vært cachet. Setter opp
caffeine da det er raskt og enkelt.

Sett opp caffeine cache og cache ms graph

---

src/main/java/no/nav/sbl/service/EnheterService.kt
src/main/resources/application.properties

Den conflicter antakeligvis med custom EnheterCache

Fjerne autowired cache for enheter

---

src/main/java/no/nav/sbl/service/EnheterService.kt

https://stackoverflow.com/questions/56137474/spring-with-kotlin-final-method-in-an-open-class-is-not-able-to-access-member

enheter cache fix

---

Dockerfile

- **Bytt til distroless java docker bilde**
- **Prøv å fikse permission issue**

distroless

---

src/main/java/no/nav/sbl/config/ServiceContext.kt
src/main/java/no/nav/sbl/service/EnheterService.kt
src/main/resources/application.properties

CachedAxsysClient har cachetid på 12 timer. Vi bruker vår egen cache med
kortere cachetid isteden.

Fiks caching fra axsys

---

.github/workflows/redis-med-passord.yaml
.nais/prod.yaml

Merges utenom arbeidstid da context blir resatt om denne deployes til prod

Bruk aiven redis i prod

---

.nais/prod.yaml
src/main/java/no/nav/sbl/config/WebSocketConfiguration.kt
src/main/java/no/nav/sbl/websocket/ContextWebSocketHandler.kt
src/test/java/no/nav/sbl/MainTest.kt

- **Revert "Error handling i WS heartbeat"**
- **Revert "Legg til scheduled task for WS heartbeat"**
- **Øk resources til prod deployment**

revert and resources

---

src/main/kotlin/no/nav/modiacontextholder/Infrastructure.kt
src/test/kotlin/no/nav/modiacontextholder/routes/ContextRoutesTest.kt

Vi har ingen grunn til å måtte skille på med og uten, og dette har
brekekt for noen.

Ignorere trailing slash

---

build.gradle.kts
src/main/kotlin/no/nav/modiacontextholder/Api.kt
src/main/kotlin/no/nav/modiacontextholder/naudit/Audit.kt
src/main/kotlin/no/nav/modiacontextholder/routes/ContextRoutes.kt
src/main/kotlin/no/nav/modiacontextholder/routes/SwaggerRoutes.kt
src/main/resources/openapi/documentation.yaml

Plugin for IntelliJ liker ikke varargs. Etter å ha erstattet varargs med liste så fikk jeg generert OpenAPI-dokumentasjon fra koden.

Legg til OpenAPI-dokumentasjon og Swagger route

---

.nais/dev.yaml
.nais/prod.yaml
build.gradle.kts
src/main/kotlin/no/nav/modiacontextholder/AppModule.kt
src/main/kotlin/no/nav/modiacontextholder/config/Configuration.kt
src/main/kotlin/no/nav/modiacontextholder/mock/MockAzureADService.kt
src/main/kotlin/no/nav/modiacontextholder/routes/DecoratorRoutes.kt
src/main/kotlin/no/nav/modiacontextholder/service/AzureADService.kt
src/main/kotlin/no/nav/modiacontextholder/service/EnheterService.kt
src/main/kotlin/no/nav/modiacontextholder/service/VeilederService.kt
src/main/kotlin/no/nav/modiacontextholder/utils/Cache.kt
src/test/kotlin/no/nav/modiacontextholder/rest/TestApplication.kt
src/test/kotlin/no/nav/modiacontextholder/routes/DecoratorRoutesTest.kt
src/test/kotlin/no/nav/modiacontextholder/service/AzureADServiceTest.kt
src/test/kotlin/no/nav/modiacontextholder/service/EnheterServiceTest.kt
src/test/kotlin/no/nav/modiacontextholder/utils/DistributedCacheTest.kt

En ny redis instans brukes som shared cache. Cache interfacen er nå
implementert av en delegatør til Caffeine og redis.

Implementere redis cache

---

src/main/kotlin/no/nav/modiacontextholder/AppModule.kt
src/main/kotlin/no/nav/modiacontextholder/routes/DecoratorRoutes.kt
src/main/kotlin/no/nav/modiacontextholder/service/EnheterService.kt
src/main/kotlin/no/nav/modiacontextholder/service/unleash/ToggleableFeatures.kt
src/test/kotlin/no/nav/modiacontextholder/routes/DecoratorRoutesTest.kt
src/test/kotlin/no/nav/modiacontextholder/service/EnheterServiceTest.kt

Bruk Entra ID (AzureService) for å hente tilganger

---

.nais/dev.yaml
.nais/prod.yaml
src/main/kotlin/no/nav/modiacontextholder/AppModule.kt
src/main/kotlin/no/nav/modiacontextholder/config/Configuration.kt
src/test/kotlin/no/nav/modiacontextholder/rest/TestApplication.kt

Litt unødvendig å ha to instanser her

Bruk samme redis instans for pubsub og cache

---

.nais/dev.yaml
.nais/prod.yaml

Legger til familie-ba-sak på inbound rules i dev og prod

Legg til familie-ba-sak i dev og prod

---

.nais/dev.yaml
.nais/prod.yaml

Bytter ut applikasjon fra #492 fra `familie-ba-sak` til `familie-integrasjoner`

Bytt ut familie-ba-sak med familie-integrasjoner i dev og prod

---

.nais/dev.yaml
.nais/prod.yaml

Bytter fra gcp til fss for familie-integrasjoner

Bytt cluster for familie-integrasjoner
